kind: Service
apiVersion: v1
metadata:
  name: notes-app-frontend-service
  namespace: notes-app-ns
  labels:
    app: notes-app-frontend-service

spec:
  selector:
    app: notes-app-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
