name: CI/CD

on:
  push:
    branches: [main]

jobs:
  django-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Run Django system check
        working-directory: ./backend
        env:
          DB_NAME: dummy
          DB_USER: dummy
          DB_PASSWORD: dummy
          DB_HOST: localhost
          DB_PORT: 5432
        run: python manage.py check

  build-and-push:
    needs: django-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            harshal345/notes-app_backend:latest
            harshal345/notes-app_backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            harshal345/notes-app_frontend:latest
            harshal345/notes-app_frontend:${{ github.sha }}
